/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.KhuyenMaiDAO;
import dao.VoucherDAO;
import entity.KhuyenMai;
import entity.Voucher;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.XDate;

/**
 *
 * @author luuvi
 */
public class KhuyenMai_Views extends javax.swing.JPanel {

    private int index;

    private final KhuyenMaiDAO daoKM;
    private final VoucherDAO daoVoucher;

    private DefaultTableModel modelKM;
    private DefaultTableModel modelVoucher;

    // Các biến sau có chức năng phân trang CT Voucher
    double soTrangLe1;
    int soTrang1;
    int tienLui1 = 0;
    int viTriTrang1 = 1;

    // Các biến sau có chức năng phân trang CTKM
    double soTrangLe2;
    int soTrang2;
    int tienLui2 = 0;
    int viTriTrang2 = 1;

    public KhuyenMai_Views() {
        initComponents();

        daoKM = new KhuyenMaiDAO();
        daoVoucher = new VoucherDAO();

        setSoTrang1();
        setSoTrang2();

        loadDataToTableVoucher(daoVoucher.phanTrangVoucher(tienLui1));
        loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui2));
    }

    private void loadDataToTableVoucher(List<Voucher> list) {
        DefaultTableModel modelVoucher = (DefaultTableModel) tblVoucher.getModel();
        modelVoucher.setRowCount(0);
        int i = 1;
        for (Voucher voucher : list) {
            modelVoucher.addRow(new Object[]{
                i++,
                voucher.getTen(),
                voucher.getMoTa(),
                voucher.getNgayBD(),
                voucher.getNgayKT(),
                voucher.getGiamGia(),
                voucher.getGiaToiDa(),
                voucher.getDonToiThieu(),
                voucher.getTrangThai()
            });
        }
    }

    private void loadDataToTableCTKM(List<KhuyenMai> list) {
        DefaultTableModel modelCTKM = (DefaultTableModel) tblCTKhuyenMai.getModel();
        modelCTKM.setRowCount(0);
        int i = 1;
        for (KhuyenMai khuyenMai : list) {
            modelCTKM.addRow(new Object[]{
                i++,
                khuyenMai.getTen(),
                khuyenMai.getMoTa(),
                khuyenMai.getNgayBD(),
                khuyenMai.getNgayKT(),
                khuyenMai.getGiamGia(),
                khuyenMai.getTrangThai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTenVoucher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTaVoucher = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtNgayBDVoucher = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayKTVoucher = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGiamGiaVoucher = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtGiamToiDa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDonToiThieu = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        rdoHoatDong1 = new javax.swing.JRadioButton();
        rdoTamDung1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        btnFist1 = new javax.swing.JButton();
        btnPre1 = new javax.swing.JButton();
        lblSoTrangVoucher = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTenCT1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMoTa1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtNgayBD1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayKT1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGiamGia1 = new javax.swing.JTextField();
        btnNew1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rdoHoatDong = new javax.swing.JRadioButton();
        rdoTamDung = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCTKhuyenMai = new javax.swing.JTable();
        btnFist2 = new javax.swing.JButton();
        btnPre2 = new javax.swing.JButton();
        lblSoTrangCTKM = new javax.swing.JLabel();
        btnNext2 = new javax.swing.JButton();
        btnLast2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSPCT = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ CHƯƠNG TRÌNH KHUYẾN MÃI & VOUCHER");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThem.setBackground(new java.awt.Color(102, 255, 51));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên chương trình");

        jLabel3.setText("Mô tả");

        txtMoTaVoucher.setColumns(20);
        txtMoTaVoucher.setRows(5);
        jScrollPane3.setViewportView(txtMoTaVoucher);

        jLabel4.setText("Ngày bắt đầu");

        txtNgayBDVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBDVoucherActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày kết thúc");

        jLabel10.setText("Giảm giá");

        jLabel11.setText("Gía tối đa");

        txtGiamToiDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamToiDaActionPerformed(evt);
            }
        });

        jLabel12.setText("Đơn tối thiểu");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLabel15.setText("Trạng thái");

        buttonGroup2.add(rdoHoatDong1);
        rdoHoatDong1.setText("Hoạt động");

        buttonGroup2.add(rdoTamDung1);
        rdoTamDung1.setText("Tạm dừng");

        jTextField1.setText("%");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên", "Mô Tả", "Ngày BĐ", "Ngày KT", "Giảm Giá", "Gía Tối Đa", "Đơn Tối Thiểu", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucher.setPreferredSize(new java.awt.Dimension(600, 80));
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblVoucher);

        btnFist1.setText("|<");
        btnFist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFist1ActionPerformed(evt);
            }
        });

        btnPre1.setText("<<");
        btnPre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPre1ActionPerformed(evt);
            }
        });

        lblSoTrangVoucher.setText("SoTrang");

        btnNext1.setText(">>");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnLast1.setText(">|");
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnFist1)
                        .addGap(18, 18, 18)
                        .addComponent(btnPre1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoTrangVoucher)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext1)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFist1)
                    .addComponent(btnPre1)
                    .addComponent(lblSoTrangVoucher)
                    .addComponent(btnNext1)
                    .addComponent(btnLast1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayBDVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGiamGiaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoHoatDong1)
                                            .addComponent(txtNgayKTVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rdoTamDung1)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenVoucher)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNew))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua)
                                    .addComponent(btnThem))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rdoHoatDong1, rdoTamDung1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNew, btnSua, btnThem});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNew)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayBDVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtNgayKTVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rdoHoatDong1))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTamDung1)
                    .addComponent(txtGiamGiaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rdoHoatDong1, rdoTamDung1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNew, btnSua, btnThem});

        jTabbedPane1.addTab("Voucher", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThem1.setBackground(new java.awt.Color(102, 255, 102));
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(255, 255, 0));
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tên chương trình");

        jLabel7.setText("Mô tả");

        txtMoTa1.setColumns(20);
        txtMoTa1.setRows(5);
        jScrollPane5.setViewportView(txtMoTa1);

        jLabel8.setText("Ngày bắt đầu");

        jLabel9.setText("Ngày kết thúc");

        jLabel13.setText("Giảm giá");

        btnNew1.setText("New");
        btnNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Trạng thái");

        buttonGroup1.add(rdoHoatDong);
        rdoHoatDong.setText("Hoạt động");

        buttonGroup1.add(rdoTamDung);
        rdoTamDung.setText("Tạm ngừng");

        jTextField2.setText("%");

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        jLabel16.setText("Danh sách CTKM");

        tblCTKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên", "Mô Tả", "Ngày BĐ", "Ngày KT", "Giảm Gía", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCTKhuyenMai);

        btnFist2.setText("|<");
        btnFist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFist2ActionPerformed(evt);
            }
        });

        btnPre2.setText("<<");
        btnPre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPre2ActionPerformed(evt);
            }
        });

        lblSoTrangCTKM.setText("SoTrangCTKM");

        btnNext2.setText(">>");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        btnLast2.setText(">|");
        btnLast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnFist2)
                        .addGap(18, 18, 18)
                        .addComponent(btnPre2)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoTrangCTKM)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext2)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFist2)
                    .addComponent(btnPre2)
                    .addComponent(lblSoTrangCTKM)
                    .addComponent(btnNext2)
                    .addComponent(btnLast2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        jLabel17.setText("Danh sách sản phẩm chi tiết");

        btnSearch.setText("Search");

        tblSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SPCT", "Tên Sản Phẩm", "Khuyến Mãi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSPCT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSearch))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayKT1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayBD1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtTenCT1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGiamGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdoHoatDong)
                    .addComponent(rdoTamDung)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSua1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew1)))
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNew1, btnSua1, btnThem1});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTenCT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNgayBD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayKT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiamGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(rdoHoatDong))
                        .addGap(18, 18, 18)
                        .addComponent(rdoTamDung)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem1)
                            .addComponent(btnSua1)
                            .addComponent(btnNew1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNew1, btnSua1, btnThem1});

        jTabbedPane1.addTab("CT Khuyến Mãi", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearFormVoucher();
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblCTKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTKhuyenMaiMouseClicked
        index = tblCTKhuyenMai.getSelectedRow();
        this.showDetailCTKhuyenMai(index);
    }//GEN-LAST:event_tblCTKhuyenMaiMouseClicked

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // Lấy thông tin từ form khuyến mãi
        KhuyenMai khuyenMai = getFormKM();

        try {
            // Thực hiện thêm khuyến mãi
            daoKM.insert(khuyenMai);

            JOptionPane.showMessageDialog(this, "Thêm khuyến mãi thành công!");
            clearFormCTKhuyenMai(); // Xóa form sau khi thêm thành công
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui1)); // Cập nhật lại bảng hiển thị khuyến mãi
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm khuyến mãi thất bại!");
        }

    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew1ActionPerformed
        clearFormCTKhuyenMai();
    }//GEN-LAST:event_btnNew1ActionPerformed

    private void txtGiamToiDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamToiDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamToiDaActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // Lấy thông tin từ form khuyến mãi
        KhuyenMai khuyenMai = getFormKM();
        khuyenMai.setChuongTrinh_id((int) tblCTKhuyenMai.getValueAt(index, 0)); // Lấy ID từ bảng để sửa

        try {
            // Thực hiện cập nhật khuyến mãi
            daoKM.update(khuyenMai);
            JOptionPane.showMessageDialog(this, "Cập nhật khuyến mãi thành công!");
            clearFormCTKhuyenMai(); // Xóa form sau khi cập nhật thành công
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui1)); // Cập nhật lại bảng hiển thị khuyến mãi
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cập nhật khuyến mãi thất bại!");
        }

    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ form voucher
        Voucher voucher = getFormVoucher();
        try {
            // Thực hiện thêm voucher
            daoVoucher.insert(voucher);
            JOptionPane.showMessageDialog(this, "Thêm voucher thành công!");
            clearFormVoucher(); // Xóa form sau khi thêm thành công
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui1)); // Cập nhật lại bảng hiển thị voucher
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm voucher thất bại!");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ form voucher
        Voucher voucher = getFormVoucher();
        voucher.setVoucher_id((int) tblVoucher.getValueAt(index, 0)); // Lấy ID từ bảng để sửa

        try {
            // Thực hiện cập nhật voucher
            daoVoucher.update(voucher);
            JOptionPane.showMessageDialog(this, "Cập nhật voucher thành công!");
            clearFormVoucher(); // Xóa form sau khi cập nhật thành công
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui1)); // Cập nhật lại bảng hiển thị voucher
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cập nhật voucher thất bại!");
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtNgayBDVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBDVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBDVoucherActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        // TODO add your handling code here:
        index = tblVoucher.getSelectedRow();
        this.showDetailVoucher(index);
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnFist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFist1ActionPerformed
        // TODO add your handling code here:
        first1();
    }//GEN-LAST:event_btnFist1ActionPerformed

    private void btnPre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPre1ActionPerformed
        // TODO add your handling code here:
        pre1();
    }//GEN-LAST:event_btnPre1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        next1();
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
        last1();
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void btnFist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFist2ActionPerformed
        // TODO add your handling code here:
        first2();
    }//GEN-LAST:event_btnFist2ActionPerformed

    private void btnPre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPre2ActionPerformed
        // TODO add your handling code here:
        pre2();
    }//GEN-LAST:event_btnPre2ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
        next2();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnLast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast2ActionPerformed
        // TODO add your handling code here:
        last2();
    }//GEN-LAST:event_btnLast2ActionPerformed

    private void next1() {
        if (viTriTrang1 < soTrang1) {
            viTriTrang1++;
            tienLui1 += 5;
            loadDataToTableVoucher(daoVoucher.phanTrangVoucher(tienLui1));
            setSoTrang1();
        } else {
            first1();
        }
    }

    private void first1() {
        tienLui1 = 0;
        viTriTrang1 = 1;
        setSoTrang1();
        loadDataToTableVoucher(daoVoucher.phanTrangVoucher(tienLui1));
    }

    private void pre1() {
        if (viTriTrang1 > 1) {
            viTriTrang1--;
            tienLui1 -= 5;
            loadDataToTableVoucher(daoVoucher.phanTrangVoucher(tienLui1));
            setSoTrang1();
        } else {
            last1();
        }
    }

    private void last1() {
        tienLui1 = soTrang1 * 5 - 5;
        viTriTrang1 = soTrang1;
        setSoTrang1();
        loadDataToTableVoucher(daoVoucher.phanTrangVoucher(tienLui1));
    }

    private void next2() {
        if (viTriTrang2 < soTrang2) {
            viTriTrang2++;
            tienLui2 += 5;
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui2));
            setSoTrang2();
        } else {
            first2();
        }
    }

    private void first2() {
        tienLui2 = 0;
        viTriTrang2 = 1;
        setSoTrang2();
        loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui2));
    }

    private void pre2() {
        if (viTriTrang2 > 1) {
            viTriTrang2--;
            tienLui2 -= 5;
            loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui2));
            setSoTrang2();
        } else {
            last2();
        }
    }

    private void last2() {
        tienLui2 = soTrang2 * 5 - 5;
        viTriTrang2 = soTrang2;
        setSoTrang2();
        loadDataToTableCTKM(daoKM.phanTrangCTKM(tienLui2));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFist1;
    private javax.swing.JButton btnFist2;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnLast2;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNew1;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnPre1;
    private javax.swing.JButton btnPre2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblSoTrangCTKM;
    private javax.swing.JLabel lblSoTrangVoucher;
    private javax.swing.JRadioButton rdoHoatDong;
    private javax.swing.JRadioButton rdoHoatDong1;
    private javax.swing.JRadioButton rdoTamDung;
    private javax.swing.JRadioButton rdoTamDung1;
    private javax.swing.JTable tblCTKhuyenMai;
    private javax.swing.JTable tblSPCT;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtDonToiThieu;
    private javax.swing.JTextField txtGiamGia1;
    private javax.swing.JTextField txtGiamGiaVoucher;
    private javax.swing.JTextField txtGiamToiDa;
    private javax.swing.JTextArea txtMoTa1;
    private javax.swing.JTextArea txtMoTaVoucher;
    private javax.swing.JTextField txtNgayBD1;
    private javax.swing.JTextField txtNgayBDVoucher;
    private javax.swing.JTextField txtNgayKT1;
    private javax.swing.JTextField txtNgayKTVoucher;
    private javax.swing.JTextField txtTenCT1;
    private javax.swing.JTextField txtTenVoucher;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void showDetailVoucher(int index) {
        txtTenVoucher.setText((String) tblVoucher.getValueAt(index, 1));
        txtMoTaVoucher.setText((String) tblVoucher.getValueAt(index, 2));
        // Sử dụng XDate để định dạng ngày thành chuỗi
        Date ngayBD = (Date) tblVoucher.getValueAt(index, 3);
        Date ngayKT = (Date) tblVoucher.getValueAt(index, 4);

        // Đặt các ngày đã định dạng vào các trường văn bản
        txtNgayBDVoucher.setText(XDate.toString(ngayBD, "yyyy-MM-dd"));
        txtNgayKTVoucher.setText(XDate.toString(ngayKT, "yyyy-MM-dd"));

        txtGiamGiaVoucher.setText(tblVoucher.getValueAt(index, 5).toString());
        txtGiamToiDa.setText(tblVoucher.getValueAt(index, 6).toString());
        txtDonToiThieu.setText(tblVoucher.getValueAt(index, 7).toString());

        rdoHoatDong1.setSelected(tblVoucher.getValueAt(index, 8).equals("Hoạt động"));

        rdoTamDung1.setSelected(tblVoucher.getValueAt(index, 8).equals("Tạm dừng"));

        tblVoucher.setRowSelectionInterval(index, index);
    }

    private void showDetailCTKhuyenMai(int index) {
        txtTenCT1.setText((String) tblCTKhuyenMai.getValueAt(index, 1));
        txtMoTa1.setText((String) tblCTKhuyenMai.getValueAt(index, 2));
        // Sử dụng XDate để định dạng ngày thành chuỗi
        Date ngayBD = (Date) tblCTKhuyenMai.getValueAt(index, 3);
        Date ngayKT = (Date) tblCTKhuyenMai.getValueAt(index, 4);

        // Đặt các ngày đã định dạng vào các trường văn bản
        txtNgayBD1.setText(XDate.toString(ngayBD, "yyyy-MM-dd"));
        txtNgayKT1.setText(XDate.toString(ngayKT, "yyyy-MM-dd"));

        txtGiamGia1.setText(tblCTKhuyenMai.getValueAt(index, 5).toString());

        rdoHoatDong.setSelected(tblCTKhuyenMai.getValueAt(index, 6).equals("Hoạt động"));

        rdoTamDung.setSelected(tblCTKhuyenMai.getValueAt(index, 6).equals("Tạm dừng"));

        tblCTKhuyenMai.setRowSelectionInterval(index, index);
    }

    private void clearFormVoucher() {
        txtTenVoucher.setText("");
        txtMoTaVoucher.setText("");
        txtNgayBDVoucher.setText("");
        txtNgayKTVoucher.setText("");
        txtGiamGiaVoucher.setText("");
        txtGiamToiDa.setText("");
        txtDonToiThieu.setText("");
    }

    private void clearFormCTKhuyenMai() {
        txtTenCT1.setText("");
        txtMoTa1.setText("");
        txtNgayBD1.setText("");
        txtNgayKT1.setText("");
        txtGiamGia1.setText("");
    }

    private KhuyenMai getFormKM() {
        KhuyenMai khuyenMai = new KhuyenMai();

        khuyenMai.setTen(txtTenCT1.getText());
        khuyenMai.setMoTa(txtMoTa1.getText());

        String ngayBDStr = txtNgayBD1.getText();
        Date ngayBD = XDate.toDate(ngayBDStr, "yyyy-MM-dd");
        khuyenMai.setNgayBD(ngayBD);

        String ngayKTStr = txtNgayKT1.getText();
        Date ngayKT = XDate.toDate(ngayKTStr, "yyyy-MM-dd");
        khuyenMai.setNgayKT(ngayKT);

        khuyenMai.setGiamGia(Double.parseDouble(txtGiamGia1.getText()));
        if (rdoHoatDong.isSelected()) {
            khuyenMai.setTrangThai("Hoạt động");
        } else {
            khuyenMai.setTrangThai("Tạm ngừng");
        }
        return khuyenMai;
    }

    private Voucher getFormVoucher() {
        Voucher voucher = new Voucher();

        voucher.setTen(txtTenVoucher.getText());
        voucher.setMoTa(txtMoTaVoucher.getText());

        String ngayBDStr = txtNgayBDVoucher.getText();
        Date ngayBD = XDate.toDate(ngayBDStr, "yyyy-MM-dd");
        voucher.setNgayBD(ngayBD);

        String ngayKTStr = txtNgayKTVoucher.getText();
        Date ngayKT = XDate.toDate(ngayKTStr, "yyyy-MM-dd");
        voucher.setNgayKT(ngayKT);

        voucher.setGiamGia(Double.parseDouble(txtGiamGiaVoucher.getText()));
        voucher.setGiaToiDa(Double.parseDouble(txtGiamToiDa.getText()));
        voucher.setDonToiThieu(Double.parseDouble(txtDonToiThieu.getText()));

        if (rdoHoatDong1.isSelected()) {
            voucher.setTrangThai("Hoạt động");
        } else {
            voucher.setTrangThai("Tạm ngừng");
        }

        return voucher;
    }

    private void setSoTrang1() {
        soTrangLe1 = Math.ceil((double) daoVoucher.selectAll().size() / 5);
        soTrang1 = (int) soTrangLe1;
        lblSoTrangVoucher.setText(viTriTrang1 + "/" + soTrang1);
    }

    private void setSoTrang2() {
        soTrangLe2 = Math.ceil((double) daoKM.selectAll().size() / 5);
        soTrang2 = (int) soTrangLe2;
        lblSoTrangCTKM.setText(viTriTrang2 + "/" + soTrang2);
    }
}
