/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.BanHangDAO;
import dao.ChatLieuDAO;
import dao.MauSacDAO;
import dao.NhaCungCapDAO;
import dao.SanPhamChiTietDAO;
import dao.SanPhamDAO;
import dao.SizeDAO;
import entity.ChatLieu;
import entity.MauSac;
import entity.SanPham;
import entity.SanPhamChiTiet;
import entity.Size;
import java.awt.AWTException;
import java.awt.Frame;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trong Phu
 */
public class SanPhamChiTietJDialog extends javax.swing.JDialog {

    SanPhamDAO spd = new SanPhamDAO();
    SanPhamChiTietDAO spctDAO = new SanPhamChiTietDAO();
    SizeDAO sDAO = new SizeDAO();
    NhaCungCapDAO nccDAO = new NhaCungCapDAO();
    ChatLieuDAO clDAO = new ChatLieuDAO();
    MauSacDAO mauDAO = new MauSacDAO();
    int tienLui = 0;
    double soTrangLe;
    int soTrang;
    int viTriTrang = 1;
    public int counter = 0;
    MauSacDAO msd = new MauSacDAO();
    SizeDAO sd = new SizeDAO();
    ChatLieuDAO cld = new ChatLieuDAO();
    BanHangDAO bhd = new BanHangDAO();

    /**
     * Creates new form SanPhamChiTietJDialog
     *
     * @param parent
     * @param modal
     */
    public SanPhamChiTietJDialog(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setTitle("Sản phẩm chi tiết view");
        setLocationRelativeTo(null);
        //soTrang = (soTrang > 0) ? soTrang + 1 : soTrang;
        setSoTrang();
        this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
        this.setComboTenSP();
        this.setComboChatLieu();
        this.setComboMauSac();
        this.setComboSize();
        cboTenSanPhamCT.setSelectedItem(SanPham_View.ten_SP);
        cboTenSanPhamCT.setEnabled(false);
        //System.out.println(counter);
      
    }

   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblAnhSanPham = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTaSPCT = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        rdoHetHangSPCT = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        cboTenSanPhamCT = new javax.swing.JComboBox<>();
        txtSanPhamCTID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLuiSPCT = new javax.swing.JButton();
        lblSoTrangSPCT = new javax.swing.JLabel();
        btnTienSPCT = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQLSPCT = new javax.swing.JTable();
        btnTrangDau = new javax.swing.JButton();
        btnTrangCuoi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnThemSPCT = new javax.swing.JButton();
        btnSuaSPCt = new javax.swing.JButton();
        btnLamMoiSPCT = new javax.swing.JButton();
        cboSize = new javax.swing.JComboBox<>();
        cboMauSac = new javax.swing.JComboBox<>();
        cboChatLieu = new javax.swing.JComboBox<>();
        btnThemSize = new javax.swing.JButton();
        btnThemMau = new javax.swing.JButton();
        btnThemChatLieu = new javax.swing.JButton();
        btnChonAnhSPCT = new javax.swing.JButton();
        rdoConHangSPCT = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 251, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ SẢN PHẨM CHI TIẾT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tên sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Trạng thái");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mô tả");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Đơn giá");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Size");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Màu sắc");

        lblAnhSanPham.setBackground(new java.awt.Color(204, 204, 204));
        lblAnhSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/No-Image.svg.png"))); // NOI18N
        lblAnhSanPham.setOpaque(true);

        txtMoTaSPCT.setColumns(20);
        txtMoTaSPCT.setRows(5);
        jScrollPane2.setViewportView(txtMoTaSPCT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Chất liệu");

        buttonGroup1.add(rdoHetHangSPCT);
        rdoHetHangSPCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdoHetHangSPCT.setText("Hết hàng");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtSanPhamCTID.setEditable(false);
        txtSanPhamCTID.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("SPCT id");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm chi tiết"));

        btnLuiSPCT.setText("<");
        btnLuiSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuiSPCTActionPerformed(evt);
            }
        });

        lblSoTrangSPCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSoTrangSPCT.setText("SoTrangSPCT");

        btnTienSPCT.setText(">");
        btnTienSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienSPCTActionPerformed(evt);
            }
        });

        tblQLSPCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblQLSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID SPCT", "ID Sản phẩm", "Tên sản phẩm", "Trạng thái", "Mô tả", "Số lượng", "Đơn giá", "Size", "Màu sắc", "Chất liệu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLSPCTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblQLSPCT);

        btnTrangDau.setText("|<");
        btnTrangDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangDauActionPerformed(evt);
            }
        });

        btnTrangCuoi.setText(">|");
        btnTrangCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangCuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(btnTrangDau, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuiSPCT)
                .addGap(26, 26, 26)
                .addComponent(lblSoTrangSPCT)
                .addGap(18, 18, 18)
                .addComponent(btnTienSPCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrangCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnTrangCuoi, btnTrangDau});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTienSPCT)
                    .addComponent(lblSoTrangSPCT)
                    .addComponent(btnLuiSPCT)
                    .addComponent(btnTrangDau)
                    .addComponent(btnTrangCuoi))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnThemSPCT.setBackground(new java.awt.Color(0, 204, 0));
        btnThemSPCT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemSPCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add3.png"))); // NOI18N
        btnThemSPCT.setText("Thêm");
        btnThemSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPCTActionPerformed(evt);
            }
        });

        btnSuaSPCt.setBackground(new java.awt.Color(255, 204, 51));
        btnSuaSPCt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaSPCt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnSuaSPCt.setText("Sửa");
        btnSuaSPCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPCtActionPerformed(evt);
            }
        });

        btnLamMoiSPCT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLamMoiSPCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh (1).png"))); // NOI18N
        btnLamMoiSPCT.setText("Làm mới");
        btnLamMoiSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiSPCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnThemSPCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaSPCt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoiSPCT)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamMoiSPCT, btnSuaSPCt, btnThemSPCT});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSPCT)
                    .addComponent(btnSuaSPCt)
                    .addComponent(btnLamMoiSPCT))
                .addContainerGap())
        );

        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboSizeMouseClicked(evt);
            }
        });

        cboMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMauSacMouseClicked(evt);
            }
        });

        cboChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChatLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboChatLieuMouseClicked(evt);
            }
        });

        btnThemSize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSizeActionPerformed(evt);
            }
        });

        btnThemMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauActionPerformed(evt);
            }
        });

        btnThemChatLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btnThemChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChatLieuActionPerformed(evt);
            }
        });

        btnChonAnhSPCT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChonAnhSPCT.setText("Chọn ảnh");
        btnChonAnhSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChonAnhSPCTMouseClicked(evt);
            }
        });
        btnChonAnhSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhSPCTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoConHangSPCT);
        rdoConHangSPCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdoConHangSPCT.setText("Còn hàng");
        rdoConHangSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoConHangSPCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblAnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnChonAnhSPCT)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(40, 40, 40)
                                        .addComponent(rdoConHangSPCT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoHetHangSPCT))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSanPhamCTID)
                                            .addComponent(jScrollPane2)
                                            .addComponent(cboTenSanPhamCT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel16))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSoLuong)
                                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonAnhSPCT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(txtSanPhamCTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rdoHetHangSPCT)
                                            .addComponent(rdoConHangSPCT)
                                            .addComponent(jLabel3)))
                                    .addComponent(cboTenSanPhamCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel9)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThemChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPCTActionPerformed
        // TODO add your handling code here:
        this.addSPCT();
        setSoTrang();
    }//GEN-LAST:event_btnThemSPCTActionPerformed

    private void btnSuaSPCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPCtActionPerformed
        try {
            // TODO add your handling code here:
            suaSPCT();
            setSoTrang();
        } catch (AWTException ex) {
            Logger.getLogger(SanPham_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaSPCtActionPerformed

    private void btnLamMoiSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiSPCTActionPerformed
        try {
            // TODO add your handling code here:
            lamMoiFormSPCT();
        } catch (AWTException ex) {
            Logger.getLogger(SanPham_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLamMoiSPCTActionPerformed

    private void cboSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboSizeMouseClicked
        // TODO add your handling code here:
        // setComboSize();
    }//GEN-LAST:event_cboSizeMouseClicked

    private void cboMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMauSacMouseClicked
        // TODO add your handling code here:
        //  setComboMauSac();
    }//GEN-LAST:event_cboMauSacMouseClicked

    private void cboChatLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboChatLieuMouseClicked
        // TODO add your handling code here:
        // setComboChatLieu();
    }//GEN-LAST:event_cboChatLieuMouseClicked

    private void btnThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSizeActionPerformed
        // TODO add your handling code here:
        // new ThemNhanhTT_View().setVisible(true);
        //        ThemNhanhThuocTinhJDialog.tabs = 0;
        //        TrangChu tc = new TrangChu();
        //        new ThemNhanhThuocTinhJDialog(tc, true).setVisible(true);

        // Đoạn mã trong phương thức btnThemSizeActionPerformed
        ThemNhanhThuocTinhJDialog.tabs = 0;
        moDialogThuocTinh();
        setComboSize();
    }//GEN-LAST:event_btnThemSizeActionPerformed


    private void btnThemMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauActionPerformed
        // TODO add your handling code here:
        ThemNhanhThuocTinhJDialog.tabs = 1;
        moDialogThuocTinh();
        setComboMauSac();
    }//GEN-LAST:event_btnThemMauActionPerformed

    private void btnThemChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChatLieuActionPerformed
        // TODO add your handling code here:
        ThemNhanhThuocTinhJDialog.tabs = 2;
        moDialogThuocTinh();
        setComboChatLieu();
    }//GEN-LAST:event_btnThemChatLieuActionPerformed

    private void btnLuiSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuiSPCTActionPerformed
        preview();
    }//GEN-LAST:event_btnLuiSPCTActionPerformed


    private void btnTienSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienSPCTActionPerformed
        next();

    }//GEN-LAST:event_btnTienSPCTActionPerformed


    private void btnChonAnhSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonAnhSPCTMouseClicked
        // TODO add your handling code here:
//        JFileChooser jfc = new JFileChooser();
//        int result = jfc.showOpenDialog(null);
//        if (result == jfc.APPROVE_OPTION) {
//            File selectedFile = jfc.getSelectedFile();
//            try {
//                String imagePath = selectedFile.getCanonicalPath();
//                JOptionPane.showMessageDialog(this, imagePath + "");
//            } catch (IOException ex) {
//                Logger.getLogger(SanPham_View.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        }
    }//GEN-LAST:event_btnChonAnhSPCTMouseClicked

    private void btnChonAnhSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhSPCTActionPerformed
        // TODO add your handling code here:
        this.fillAnhSPCT();
    }//GEN-LAST:event_btnChonAnhSPCTActionPerformed

    private void tblQLSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLSPCTMouseClicked
        // TODO add your handling code here:
        this.showDetailSPCT();
    }//GEN-LAST:event_tblQLSPCTMouseClicked

    private void rdoConHangSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoConHangSPCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoConHangSPCTActionPerformed

    private void btnTrangDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangDauActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnTrangDauActionPerformed

    private void btnTrangCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangCuoiActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnTrangCuoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTietJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTietJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTietJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTietJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPhamChiTietJDialog dialog = new SanPhamChiTietJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnhSPCT;
    private javax.swing.JButton btnLamMoiSPCT;
    private javax.swing.JButton btnLuiSPCT;
    private javax.swing.JButton btnSuaSPCt;
    private javax.swing.JButton btnThemChatLieu;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnThemSPCT;
    private javax.swing.JButton btnThemSize;
    private javax.swing.JButton btnTienSPCT;
    private javax.swing.JButton btnTrangCuoi;
    private javax.swing.JButton btnTrangDau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChatLieu;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboTenSanPhamCT;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnhSanPham;
    private javax.swing.JLabel lblSoTrangSPCT;
    private javax.swing.JRadioButton rdoConHangSPCT;
    private javax.swing.JRadioButton rdoHetHangSPCT;
    private javax.swing.JTable tblQLSPCT;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextArea txtMoTaSPCT;
    private javax.swing.JTextField txtSanPhamCTID;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

// code cua San pham chi tiet
    //đổ dữ liệu lên bảng sản phẩm chi tiết
    private void fillTBSanPhamChiTiet(List<SanPhamChiTiet> list) {
        DefaultTableModel model = (DefaultTableModel) tblQLSPCT.getModel();
        model.setRowCount(0);
        for (SanPhamChiTiet spct : list) {
            model.addRow(new Object[]{
                spct.getsPCT_id(),
                spct.getSanPham_id(),
                spct.getSanPham(),
                spct.getTrangThai(),
                spct.getMoTa(),
                spct.getSoLuong(),
                spct.getDonGia(),
                spct.getSize(),
                spct.getMauSac(),
                spct.getChatLieu()
            });
        }
    }

    public String taoMaSPCTTuDong() {
        counter = spctDAO.selectAll().size();
        String ma = "SPCT" + String.format("%06d", ++counter);
        return ma;
    }

    //lấy dữ liệu từ form trả về 1 đối tượng sản phẩm phục vụ chức năng thêm, sửa
    SanPhamChiTiet readForm() {
        System.out.println(taoMaSPCTTuDong());
        return new SanPhamChiTiet(
                taoMaSPCTTuDong(),
                Integer.parseInt(txtSoLuong.getText().trim()),
                BigDecimal.valueOf(Double.parseDouble(txtDonGia.getText().trim())),
                sDAO.selectByGiaTri(Integer.parseInt(cboSize.getSelectedItem() + "")).getId(),
                clDAO.selectByTenChatLieu(cboChatLieu.getSelectedItem().toString()).getId(),
                1,
                lblAnhSanPham.getToolTipText(),
                mauDAO.selectByTenMau(cboMauSac.getSelectedItem() + "").getId(),
                spd.selectByName(cboTenSanPhamCT.getSelectedItem() + "").getID(),
                rdoConHangSPCT.isSelected() ? "Còn hàng" : "Hết hàng",
                txtMoTaSPCT.getText().trim());

    }

    //set dữ liệu cho cbo Tên sản phẩm
    private void setComboTenSP() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenSanPhamCT.getModel();
        model.removeAllElements();
        for (SanPham sp : spd.selectAll()) {
            model.addElement(sp.getTenSP());
        }
    }

    //set dữ liệu cho cbo size
    private void setComboSize() {
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cboSize.getModel();
        modelc.removeAllElements();
        for (Size size : sDAO.selectAll()) {
            modelc.addElement(size.getGiatri());
        }
    }

    //set dữ liệu cho cbo màu sắc
    private void setComboMauSac() {
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cboMauSac.getModel();
        modelc.removeAllElements();
        for (MauSac mauSac : mauDAO.selectAll()) {
            modelc.addElement(mauSac.getTenMau());
        }
    }

    //set dữ liệu cho cbo chất liệu
    private void setComboChatLieu() {
        DefaultComboBoxModel modelc = (DefaultComboBoxModel) cboChatLieu.getModel();
        modelc.removeAllElements();
        for (ChatLieu cl : clDAO.selectAll()) {
            modelc.addElement(cl.getTenCL());
        }
    }

    //hàm thêm sản phẩm chi tiết
    private void addSPCT() {
        if (checkFormSPCT()) {
            SanPhamChiTiet spct = readForm();
            if (spctDAO.insert(spct) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết sản phẩm thành công!!");
                this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
            } else {
                JOptionPane.showMessageDialog(this, "Thêm chi tiết sản phẩm thất bại");
            }
        }

    }

    // hàm đổ dữ liệu từ đối tượng được chọn lên các trường của form
    void showDetailSPCT() {
        int index = tblQLSPCT.getSelectedRow();
        SanPhamChiTiet spct = spctDAO.selectSPTCByID(tblQLSPCT.getValueAt(index, 0).toString());
        txtSanPhamCTID.setText(spct.getsPCT_id());
        cboTenSanPhamCT.setSelectedItem(spct.getSanPham());
        if (spct.getTrangThai().equals("Còn hàng")) {
            rdoConHangSPCT.setSelected(true);
        } else {
            rdoHetHangSPCT.setSelected(true);
        }
        ImageIcon icon = new ImageIcon(spct.getAnh());
        // Đặt kích thước cho hình ảnh
        Image image = icon.getImage().getScaledInstance(266, 266, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(image);
        // Đặt hình ảnh cho đối tượng JLabel
        lblAnhSanPham.setToolTipText(spct.getAnh());
        lblAnhSanPham.setIcon(resizedIcon);
        txtMoTaSPCT.setText(spct.getMoTa());
        txtSoLuong.setText(spct.getSoLuong() + "");
        txtDonGia.setText(spct.getDonGia() + "");
        cboSize.setSelectedItem(spct.getSize());
        cboMauSac.setSelectedItem(spct.getMauSac());
        cboChatLieu.setSelectedItem(spct.getChatLieu());
        tblQLSPCT.setRowSelectionInterval(index, index);
    }

    private void fillAnhSPCT() {
        JFileChooser jfileSelected = new JFileChooser();
        int result = jfileSelected.showOpenDialog(null);
        if (result == jfileSelected.APPROVE_OPTION) {
            File file = jfileSelected.getSelectedFile();
            String duongDanAnh = file.getAbsolutePath();

            // Kiểm tra xem tệp có phải là hình ảnh hay không
            try {
                BufferedImage image = ImageIO.read(file);
                if (image == null) {
                    JOptionPane.showMessageDialog(this, "Tệp không phải là hình ảnh!!");
                    return;
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Không thể đọc tệp hình ảnh!!");
                return;
            }

            ImageIcon icon = new ImageIcon(duongDanAnh);

            // Đặt kích thước cho hình ảnh
            Image image = icon.getImage().getScaledInstance(266, 266, Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(image);

            // Đặt hình ảnh cho đối tượng JLabel
            lblAnhSanPham.setIcon(resizedIcon);
            lblAnhSanPham.setToolTipText(duongDanAnh);
        }
    }

    // hàm này thực hiện xoá sản phẩm chi tiết
    private void xoaSanPhamChiTiet() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá spct này?", "Xoá sản phẩm chi tiết", JOptionPane.YES_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            int index = tblQLSPCT.getSelectedRow();
            String key = tblQLSPCT.getValueAt(index, 0).toString();
            try {
                if (spctDAO.delete(key) == 0) {
                    JOptionPane.showMessageDialog(this, "Xin lỗi dữ liệu này đang được sử dụng không thể xoá!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xoá chi tiết sản phẩm thành công!!");
                    this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi xoá sản phẩm chi tiết!!");
            }
        }
    }

    //hàm này thực hiện sửa spct
    private void suaSPCT() throws AWTException {
        if (tblQLSPCT.getSelectedRow() >= 0) {

            int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa chi tiết sản phẩm?", "SỬA CHI TIÊT SẢN PHẨM", JOptionPane.YES_OPTION);
            if (choice == JOptionPane.YES_OPTION) {

                if (checkFormSPCTUpdate()) {
                    try {
                        int index = tblQLSPCT.getSelectedRow();
                        SanPhamChiTiet spct = readForm();
                        String key = tblQLSPCT.getValueAt(index, 0).toString();
                        if (spctDAO.update(key, spct) > 0) {
                            fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
                            JOptionPane.showMessageDialog(this, "Sửa chi tiết sản phẩm thành công!!");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Sửa chi tiết sản phẩm thất bại");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa spct!!");
        }
    }

    // hàm này dùng để làm mới form spct
    private void lamMoiFormSPCT() throws AWTException {
        cboChatLieu.setSelectedIndex(0);
        cboMauSac.setSelectedIndex(0);
        cboSize.setSelectedIndex(0);
        cboTenSanPhamCT.setSelectedIndex(0);
        txtSanPhamCTID.setText("");
        txtDonGia.setText("");
        txtSoLuong.setText("");
        rdoConHangSPCT.setSelected(true);
        txtMoTaSPCT.setText("");
    }

// hàm này thực hiện check form để bắt người dùng nhập đúng dữ liệu cho các trường dữ liệu của sản phẩm chi tiết
    private boolean checkFormSPCT() {
//        if (txtSanPhamCTID.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "ID spct không được để trống!!");
//            txtSanPhamCTID.requestFocus();
//            return false;
//        } else if (txtSanPhamCTID.getText().trim().length() > 10) {
//            JOptionPane.showMessageDialog(this, "ID spct không được lớn hơn 10 ký tự!!");
//            txtSanPhamCTID.requestFocus();
//            return false;
//        }
        for (SanPhamChiTiet spct : spctDAO.selectAll2()) {
            if (taoMaSPCTTuDong().trim().equalsIgnoreCase(spct.getsPCT_id())) {
                JOptionPane.showMessageDialog(this, "Trùng ID spct!!");
                txtSanPhamCTID.requestFocus();
                return false;
            }
        }
        try {
            if (txtSoLuong.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Số lượng không được để trống!!");
                txtSoLuong.requestFocus();
                return false;
            }
            if (Integer.parseInt(txtSoLuong.getText().trim()) < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn hoặc bằng 0!!");
                txtSoLuong.requestFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số!!");
            txtSoLuong.requestFocus();
            return false;
        }
        try {
            if (txtDonGia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống đơn giá!!");
                txtDonGia.requestFocus();
                return false;
            } else if (Double.parseDouble(txtDonGia.getText().trim()) <= 0) {
                JOptionPane.showMessageDialog(this, "Đơn giá phải lớn hơn 0!!");
                txtDonGia.requestFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là số!!");
            txtDonGia.requestFocus();
            return false;
        }
        for (SanPhamChiTiet spct : spctDAO.selectAll2()) {
            if (spct.getSanPham().equalsIgnoreCase(cboTenSanPhamCT.getSelectedItem().toString())
                    && spct.getChatLieu().equalsIgnoreCase(cboChatLieu.getSelectedItem().toString())
                    && spct.getMauSac().equalsIgnoreCase(cboMauSac.getSelectedItem().toString())
                    && spct.getSize() == Integer.parseInt(cboSize.getSelectedItem() + "")) {
                JOptionPane.showMessageDialog(this, "Xin lỗi sản phẩm chi tiết đã tồn tại!!");
                return false;
            }
        }

        return true;
    }

    private boolean checkFormSPCTUpdate() {
        if (txtSanPhamCTID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID spct không được để trống!!");
            txtSanPhamCTID.requestFocus();
            return false;
        } else if (txtSanPhamCTID.getText().trim().length() > 10) {
            JOptionPane.showMessageDialog(this, "ID spct không được lớn hơn 10 ký tự!!");
            txtSanPhamCTID.requestFocus();
            return false;
        }
//        for (SanPhamChiTiet spct : spctDAO.selectAll2()) {
//            if (txtSanPhamCTID.getText().trim().equalsIgnoreCase(spct.getsPCT_id())) {
//                JOptionPane.showMessageDialog(this, "Trùng ID spct!!");
//                txtSanPhamCTID.requestFocus();
//                return false;
//            }
//        }

        try {
            if (txtSoLuong.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Số lượng không được để trống!!");
                txtSoLuong.requestFocus();
                return false;
            }
            if (Integer.parseInt(txtSoLuong.getText().trim()) < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn hoặc bằng 0!!");
                txtSoLuong.requestFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số!!");
            txtSoLuong.requestFocus();
            return false;
        }
        try {
            if (txtDonGia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống đơn giá!!");
                txtDonGia.requestFocus();
                return false;
            } else if (Double.parseDouble(txtDonGia.getText().trim()) <= 0) {
                JOptionPane.showMessageDialog(this, "Đơn giá phải lớn hơn 0!!");
                txtDonGia.requestFocus();
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đơn giá phải là số!!");
            txtDonGia.requestFocus();
            return false;
        }
        return true;
    }

    // hàm này sử dụng để mở dialog thêm nhanh thuộc tính
    private void moDialogThuocTinh() {
        ThemNhanhThuocTinhJDialog dialog = new ThemNhanhThuocTinhJDialog((Frame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setVisible(true);
    }

    ///Phần code này thực hiện phân trang cho spct
    private void preview() {
        // TODO add your handling code here:
        if (viTriTrang >= 2) {
            viTriTrang--;
            setSoTrang();
            tienLui -= 5;
            this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
        } else {
            last();
        }
    }

    private void next() {
        // TODO add your handling code here:

        if (viTriTrang < soTrang) {
            viTriTrang++;
            setSoTrang();
            tienLui += 5;
            this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
        } else {
            first();
        }
    }

    private void first() {
        viTriTrang = 1;
        setSoTrang();
        tienLui = 0;
        this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
    }

    private void last() {
        viTriTrang = soTrang;
        setSoTrang();
        tienLui = 5 * soTrang - 5;
        this.fillTBSanPhamChiTiet(spctDAO.phanTrangSPCT(tienLui, SanPham_View.sP_id));
    }

    private void setSoTrang() {
        soTrangLe = Math.ceil((double) spctDAO.selectSPTCByIDSP(SanPham_View.sP_id).size() / 5);
        soTrang = (int) soTrangLe;
        if (soTrang < 1) {
            soTrang += 1;
            lblSoTrangSPCT.setText(viTriTrang + "/" + soTrang);
        } else {
            lblSoTrangSPCT.setText(viTriTrang + "/" + soTrang);
        }
    }
}
