/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.Menu;
import java.awt.Color;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.XLogin;
import utils.XMenu;

/**
 *
 * @author Trong Phu
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ứng dụng bán giày tại cửa hàng LIKEY - NHÓM 1");
        //Image icon = Toolkit.getDefaultToolkit().getImage("");
        URL url = TrangChu.class.getResource("/img/nike (1).png");
        setIconImage(new ImageIcon(url).getImage());
        if (!XLogin.daDangNhap()) {
            new DangNhapJDialog(this, true).setVisible(true);
        }

        if (!XLogin.daDangNhap()) {
            System.exit(0);
        } else {
            lblThongTinDangNhap.setText("Người đăng nhập: " + XLogin.user.getHoTen() + " - " + "Chức vụ: " + XLogin.user.getVaiTro());
        }
        dongHo();
        Menu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jpnTestLuong = new javax.swing.JPanel();
        lblBanHang = new javax.swing.JLabel();
        jpnQLSP = new javax.swing.JPanel();
        lblQLSP = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jpnQLHD = new javax.swing.JPanel();
        lblQLHD = new javax.swing.JLabel();
        jpnQLNV = new javax.swing.JPanel();
        lblQLNV = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        lblThongKe = new javax.swing.JLabel();
        jpnQLKH = new javax.swing.JPanel();
        lblQLKH = new javax.swing.JLabel();
        jpnKhuyenMai = new javax.swing.JPanel();
        lblKhuyenMai = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblThongTinDangNhap = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("LIKEY");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nike.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Công cụ quản lý"))));

        jpnTestLuong.setBackground(new java.awt.Color(255, 255, 255));
        jpnTestLuong.setPreferredSize(new java.awt.Dimension(226, 70));
        jpnTestLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTestLuongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnTestLuongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnTestLuongMouseExited(evt);
            }
        });

        lblBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selling.png"))); // NOI18N
        lblBanHang.setText("Bán hàng");
        lblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBanHangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnTestLuongLayout = new javax.swing.GroupLayout(jpnTestLuong);
        jpnTestLuong.setLayout(jpnTestLuongLayout);
        jpnTestLuongLayout.setHorizontalGroup(
            jpnTestLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTestLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTestLuongLayout.setVerticalGroup(
            jpnTestLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jpnQLSP.setBackground(new java.awt.Color(255, 255, 255));
        jpnQLSP.setPreferredSize(new java.awt.Dimension(164, 70));
        jpnQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnQLSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnQLSPMouseExited(evt);
            }
        });

        lblQLSP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product-placement.png"))); // NOI18N
        lblQLSP.setText("QL Sản phẩm");
        lblQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQLSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQLSPMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnQLSPLayout = new javax.swing.GroupLayout(jpnQLSP);
        jpnQLSP.setLayout(jpnQLSPLayout);
        jpnQLSPLayout.setHorizontalGroup(
            jpnQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLSPLayout.setVerticalGroup(
            jpnQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 0, 0));
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power-button (1).png"))); // NOI18N
        lblThoat.setText("THOÁT");
        lblThoat.setOpaque(true);
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThoatMouseExited(evt);
            }
        });

        jpnQLHD.setBackground(new java.awt.Color(255, 255, 255));
        jpnQLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnQLHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnQLHDMouseExited(evt);
            }
        });

        lblQLHD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Notes.png"))); // NOI18N
        lblQLHD.setText("QL Hoá đơn");
        lblQLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQLHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQLHDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnQLHDLayout = new javax.swing.GroupLayout(jpnQLHD);
        jpnQLHD.setLayout(jpnQLHDLayout);
        jpnQLHDLayout.setHorizontalGroup(
            jpnQLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLHDLayout.setVerticalGroup(
            jpnQLHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQLHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpnQLNV.setBackground(new java.awt.Color(255, 255, 255));
        jpnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnQLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnQLNVMouseExited(evt);
            }
        });

        lblQLNV.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee.png"))); // NOI18N
        lblQLNV.setText("QL Nhân Viên");
        lblQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQLNVMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnQLNVLayout = new javax.swing.GroupLayout(jpnQLNV);
        jpnQLNV.setLayout(jpnQLNVLayout);
        jpnQLNVLayout.setHorizontalGroup(
            jpnQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLNVLayout.setVerticalGroup(
            jpnQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLNVLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        jpnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnThongKeMouseExited(evt);
            }
        });

        lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Best.png"))); // NOI18N
        lblThongKe.setText("Thống Kê");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnQLKH.setBackground(new java.awt.Color(255, 255, 255));

        lblQLKH.setBackground(new java.awt.Color(255, 255, 255));
        lblQLKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        lblQLKH.setText("QL Khách hàng");
        lblQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQLKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQLKHMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnQLKHLayout = new javax.swing.GroupLayout(jpnQLKH);
        jpnQLKH.setLayout(jpnQLKHLayout);
        jpnQLKHLayout.setHorizontalGroup(
            jpnQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQLKHLayout.setVerticalGroup(
            jpnQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLKHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));

        lblKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        lblKhuyenMai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add to basket.png"))); // NOI18N
        lblKhuyenMai.setText("QL Khuyến Mãi");
        lblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnKhuyenMaiLayout = new javax.swing.GroupLayout(jpnKhuyenMai);
        jpnKhuyenMai.setLayout(jpnKhuyenMaiLayout);
        jpnKhuyenMaiLayout.setHorizontalGroup(
            jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKhuyenMaiLayout.setVerticalGroup(
            jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnKhuyenMaiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpnQLKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnQLHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnQLSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(jpnTestLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(jpnKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTestLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThoat)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblThoiGian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThoiGian.setText("Thời Gian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lblThongTinDangNhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblThongTinDangNhap.setText("Tên người dùng: ABC - Chức vụ: Siêu nhân Đỏ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblThongTinDangNhap)
                .addContainerGap(671, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongTinDangNhap)
                .addContainerGap())
        );

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jpnView.setPreferredSize(new java.awt.Dimension(1159, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giay-the-thao-1a-jpg-1655689580-20062022084620.jpg"))); // NOI18N

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Hệ thống");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jMenuItem1.setText("Đăng nhập");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power-button (1).png"))); // NOI18N
        jMenuItem4.setText("Thoát");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thêm nhanh thuộc tính");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void jpnTestLuongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTestLuongMouseEntered
        // TODO add your handling code here:
        jpnTestLuong.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_jpnTestLuongMouseEntered

    private void jpnTestLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTestLuongMouseExited
        // TODO add your handling code here:
        jpnTestLuong.setBackground(Color.white);
    }//GEN-LAST:event_jpnTestLuongMouseExited

    private void jpnTestLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTestLuongMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jpnTestLuongMouseClicked

    private void lblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_lblBanHangMouseClicked

    private void lblQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQLSPMouseClicked

    private void lblQLHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQLHDMouseClicked

    private void lblQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQLNVMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jpnQLSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLSPMouseEntered
        // TODO add your handling code here:
        jpnQLSP.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_jpnQLSPMouseEntered

    private void jpnQLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLSPMouseExited
        // TODO add your handling code here:
        jpnQLSP.setBackground(Color.white);
    }//GEN-LAST:event_jpnQLSPMouseExited

    private void jpnQLHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLHDMouseEntered
        // TODO add your handling code here:
        jpnQLHD.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_jpnQLHDMouseEntered

    private void jpnQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLNVMouseEntered
        // TODO add your handling code here:
        jpnQLNV.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_jpnQLNVMouseEntered

    private void jpnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThongKeMouseEntered
        // TODO add your handling code here:
        jpnThongKe.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_jpnThongKeMouseEntered

    private void jpnQLHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLHDMouseExited
        // TODO add your handling code here:
        jpnQLHD.setBackground(Color.white);
    }//GEN-LAST:event_jpnQLHDMouseExited

    private void jpnQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnQLNVMouseExited
        // TODO add your handling code here:
        jpnQLNV.setBackground(Color.white);
    }//GEN-LAST:event_jpnQLNVMouseExited

    private void jpnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnThongKeMouseExited
        // TODO add your handling code here:
        jpnThongKe.setBackground(Color.white);
    }//GEN-LAST:event_jpnThongKeMouseExited

    private void lblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseEntered
        // TODO add your handling code here:
        jpnThongKe.setBackground(this.setMau(211, 211, 211));

    }//GEN-LAST:event_lblThongKeMouseEntered

    private void lblThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseExited
        // TODO add your handling code here:
        jpnThongKe.setBackground(Color.white);
    }//GEN-LAST:event_lblThongKeMouseExited

    private void lblQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNVMouseEntered
        // TODO add your handling code here:
        jpnQLNV.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_lblQLNVMouseEntered

    private void lblQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLNVMouseExited
        // TODO add your handling code here:
        jpnQLNV.setBackground(Color.white);
    }//GEN-LAST:event_lblQLNVMouseExited

    private void lblQLHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLHDMouseEntered
        // TODO add your handling code here:
        jpnQLHD.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_lblQLHDMouseEntered

    private void lblQLHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLHDMouseExited
        // TODO add your handling code here:
        jpnQLHD.setBackground(Color.white);
    }//GEN-LAST:event_lblQLHDMouseExited

    private void lblQLSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSPMouseEntered
        // TODO add your handling code here:
        jpnQLSP.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_lblQLSPMouseEntered

    private void lblQLSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSPMouseExited
        // TODO add your handling code here:
        jpnQLSP.setBackground(Color.white);
    }//GEN-LAST:event_lblQLSPMouseExited

    private void lblBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseEntered
        // TODO add your handling code here:
        jpnTestLuong.setBackground(this.setMau(211, 211, 211));
    }//GEN-LAST:event_lblBanHangMouseEntered

    private void lblBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangMouseExited
        // TODO add your handling code here:
        jpnTestLuong.setBackground(Color.white);
    }//GEN-LAST:event_lblBanHangMouseExited

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?","THOAT",JOptionPane.YES_OPTION);
        if(choice  == JOptionPane.YES_OPTION){
             System.exit(0);
        }
       
    }//GEN-LAST:event_lblThoatMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new ThemNhanhThuocTinhJDialog(this, true).setVisible(true);

    }//GEN-LAST:event_jMenu2MouseClicked

    private void lblQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLKHMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblQLKHMouseClicked

    private void lblQLKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLKHMouseEntered
        // TODO add your handling code here:

        jpnQLKH.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_lblQLKHMouseEntered

    private void lblQLKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLKHMouseExited
        // TODO add your handling code here:
        jpnQLKH.setBackground(Color.white);
    }//GEN-LAST:event_lblQLKHMouseExited

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void lblThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseEntered
        // TODO add your handling code here:
        lblThoat.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_lblThoatMouseEntered

    private void lblThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseExited
        // TODO add your handling code here:
        lblThoat.setBackground(Color.white);
    }//GEN-LAST:event_lblThoatMouseExited

    private void lblKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseExited
        // TODO add your handling code here:
        jpnKhuyenMai.setBackground(Color.white);
    }//GEN-LAST:event_lblKhuyenMaiMouseExited

    private void lblKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseEntered
        // TODO add your handling code here:
        jpnKhuyenMai.setBackground(setMau(211, 211, 211));
    }//GEN-LAST:event_lblKhuyenMaiMouseEntered

    private void lblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblKhuyenMaiMouseClicked

    /**
     * @param args the command line arguments
     */

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TrangChu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPanel jpnKhuyenMai;
    private javax.swing.JPanel jpnQLHD;
    private javax.swing.JPanel jpnQLKH;
    private javax.swing.JPanel jpnQLNV;
    private javax.swing.JPanel jpnQLSP;
    private javax.swing.JPanel jpnTestLuong;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblQLHD;
    private javax.swing.JLabel lblQLKH;
    private javax.swing.JLabel lblQLNV;
    private javax.swing.JLabel lblQLSP;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThongTinDangNhap;
    // End of variables declaration//GEN-END:variables
    private void dongHo() {
        Thread t = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                    Date now = new Date();
                    SimpleDateFormat fomater = new SimpleDateFormat("dd-MM-yyyy | hh:mm:ss aa");
                    String time = fomater.format(now);
                    lblThoiGian.setText(time);
                }
            }
        };
        t.start();
    }

    Color setMau(int red, int green, int blue) {
        return new Color(red, green, blue);
    }

    private void Menu() {
        XMenu xmenu = new XMenu(jpnView);
        List<Menu> listMN = new ArrayList<>();
        listMN.add(new Menu("BanHang", jpnTestLuong, lblBanHang));
        listMN.add(new Menu("ThongKe", jpnThongKe, lblThongKe));
        listMN.add(new Menu("HoaDon", jpnQLHD, lblQLHD));
        listMN.add(new Menu("KhuyenMai", jpnKhuyenMai, lblKhuyenMai));
        listMN.add(new Menu("SanPham", jpnQLSP, lblQLSP));
        listMN.add(new Menu("NhanVien", jpnQLNV, lblQLNV));
        listMN.add(new Menu("KhachHang", jpnQLKH, lblQLKH));
        xmenu.setEvent(listMN);
    }

    private void dangNhap() {
        if (XLogin.daDangNhap()) {
            JOptionPane.showMessageDialog(this, "Bạn đã đăng nhập trước đó \n Cần đăng xuất để thực hiện đăng nhập lại!");
        }
    }

    private void dangXuat() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?", "ĐĂNG XUẤT", JOptionPane.YES_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            XLogin.dangXuat();
            this.dispose();
            new TrangChu().setVisible(true);
        }
    }

//    private void moDoiMatKhau() {
//        new DoiMatKhau_Dialog(this, true).setVisible(true);
//    }

}
